# Site settings
title: RubyMotion Adventures - The MotionInMotion Blog
email: info@fluffyjack.com
description: "RubyMotion tutorials, tips, guides, and fun facts. New posts on no schdule other than \"post often\""
baseurl: ""
url: "http://blog.motioninmotion.tv"
twitter_username: RubyMotionTV
github_username:  FluffyJack
timezone: Australia/Sydney

# Build settings
markdown: redcarpet
permalink: /:title
